name: build

on:
    push:
        branches:
            - main
        paths:
            - 'check-docker/**'
    workflow_dispatch:

jobs:
    build:
        name: コンパイル
        runs-on: ubuntu-latest

        steps:
        - name: ソースコードを取得
          uses: actions/checkout@v4

        - name: Rust言語環境の準備
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Cargoを使ってビルドする
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --manifest-path check-docker/Cargo.toml
